#!/bin/sh

source /root/common.sh

msg "killing red if up ..."
killall red 2&>1 /dev/null
msg "killing red if up [ ok ]"

msg "starting red as a daemon ..."
red -v --dest-ip=168.254.1.1 &
msg "starting red as a daemon [ ok ]"
