#!/bin/sh

source /root/common.sh

msg "killing red if up ..."
killall red 2&>1 /dev/null
msg "killing red if up [ ok ]"

msg "starting red as a daemon ..."
/usr/bin/red -v --dest-ip=169.254.1.1 >> /var/log/messages 2>&1 &
msg "starting red as a daemon [ ok ]"
