# Sysam ERG
# *** source this file ***

mkdir -p ${DIR_ERG}/targetfs/etc/rc.d

cat >  ${DIR_ERG}/targetfs/etc/rc.d/startup<< "EOF"
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
# remove dark blue
printf %b '\e]4;4;#6495ed\a'
cat /etc/motd
EOF

chmod 755 ${DIR_ERG}/targetfs/etc/rc.d/startup

cat > ${DIR_ERG}/targetfs/etc/inittab<< "EOF"
# /etc/inittab
::sysinit:/bin/sh /etc/rc.d/startup
EOF

echo "${console}::respawn:-/bin/sh" >> ${DIR_ERG}/targetfs/etc/inittab
